package com.mxrpheus.configurator.repository.reference.motherboard;

import com.mxrpheus.configurator.model.reference.motherboard.MotherboardIntegratedGraphicsReference;
import com.mxrpheus.configurator.repository.reference.BaseReferenceRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface MotherboardIntegratedGraphicsRepository extends BaseReferenceRepository<MotherboardIntegratedGraphicsReference> {}